### ISSUE TITLE
About SynologyPhotos

### ISSUE THREAD

**Issue by bdrwu** [007revad/Video_Station_for_DSM_722#17]
SynologyPhotos is also related to AME
The new DSM will also refuse to install the old version.
Is it possible to also install older versions of SynologyPhotos?

**Comment by 007revad** [comment]
The current version of Synology Photos just needs the HEIC codec be installed.

If you run Video_Station_for_DSM_722 it will install the previous Advanced Media Extensions so you can enable HEVC (which includes HEIC).

Then you can uninstall Video Station and Media Server if you don't need those.
