### ISSUE TITLE
AME error after installation

### ISSUE THREAD

**Issue by SidYuri** [007revad/Video_Station_for_DSM_722#19]
![изображение](https://github.com/user-attachments/assets/fb3c9e65-6c88-4691-9c95-dd525ebc2c0d)

After running the script and opening AME, a window with an error is displayed: 'Unable to perform the operation. Please contact Synology technical support' (as shown in the screenshot)
Sorry, I'm using a translator.

**Comment by SidYuri** [comment]
ARC Loader 24.09.10
NAS: ds920+
DSM: 7.2.2

**Comment by 007revad** [comment]
In package center what is the version shown for AME? It should be 30.1.0-3305

Or maybe Synology is blocking AME from downloading the HEVC codec when DSM is not running on a genuine Synology NAS.

**Comment by 007revad** [comment]
The 'Unable to perform the operation. Please contact Synology technical support' is a generic error message that DSM uses for a lot of different network or internet issues. Sometimes checking the date and time are set correctly fixes it. Or changing the DNS server addresses. Sometimes it's because Synology's server is temporarily having issues.

**Comment by SidYuri** [comment]
Changing the DNS did not help..
As I understand it, I'm the only one with a problem. ((((
Thank you. 
Unfortunately, I have to put up with it, since it started from the very beginning after installing 7.2.2.
Every time I update your script, I try again.

**Comment by 007revad** [comment]
I just got the same 'Unable to perform the operation. Please contact Synology technical support'" error in Container Manager when trying to download a docker image. There maybe a bug in DSM 7.2.2

**Comment by SidYuri** [comment]
Something else is interesting. I installed the same DSM version completely in parallel and everything works on it .

**Comment by 007revad** [comment]
That is interesting.

Synology recalled DSM 7.2.2-7280**3** and replaced it with 7.2.2-7280**6**. Can you check which versions you have installed.

**Comment by SidYuri** [comment]
I tried it on 73803 before. Yesterday I updated it to 73806. same thing...

**Comment by SidYuri** [comment]
Oh, 72803 and 72806

**Comment by 007revad** [comment]
Try uninstalling Video Station and AME then run the script again.
