### ISSUE TITLE
Aborts if VideoStation is present but has been stopped

### ISSUE THREAD

**Issue by HaukeMEYN** [007revad/Video_Station_for_DSM_722#24]
Hi, I did use the script just after I migrated from an older DSM6 based DS to a one using DSM7.2.2. That had the VideoStation still installed but stopped as no longer compatible to the current system. When running the script it stopped with an error. The result shown was:
Video_Station_for_DSM_722 v1.2.7
DS920+ DSM 7.2.2-72806 
CPU geminilake x86_64
Running from: /volume1/backup/HW/Synology_DS920+/Migraton/Video_Station_for_DSM_722-1.2.7/videostation_for_722.sh
Using CPU type: x86_64
  Uninstalling [0;36mAdvanced Media Extensions[0m.Line 300: [41mERROR[0m Uninstalling [0;36mAdvanced Media Extensions[0m failed!
progstatus called from package_uninstall line 420

I did then uninstall the existing VideoStation app from the package center and did run the script again. It was then successful.
The script may be made more robust to check if VideoStation is already installed and if the version is latest/correct keep it and otherwise uninstall it before attempting to load it.

**Comment by 007revad** [comment]
Thanks.

So when you updated to DSM 7.2.2 it didn't tell you to uninstall Video Station first?

It never occurred to me that Video Station would need to be uninstalled because when updating from DSM 7.2.1 to 7.2.2 DSM insists that you uninstall Video Station first.

**Comment by HaukeMEYN** [comment]
Yeah, regularly yes. Though, I migrated from a DSM6 system to a DSM7 system using the Synology Migration Manager. The left the Video Station installed but stopped in the system...

**Comment by 007revad** [comment]
@HaukeMEYN  I've made some changes in [v1.2.8](https://github.com/007revad/Video_Station_for_DSM_722/releases/tag/v1.2.8)

- Changed to uninstall Video Station first if wrong version of Video Station still installed after migration. Issue #24
- Added Synology China package download URL for users in China.
