### ISSUE TITLE
Script doesn't install Advanced Media Extension 

### ISSUE THREAD

**Issue by tmkklivecom** [007revad/Video_Station_for_DSM_722#3]
NAS: ds918+
DSM: 7.2.2

**Comment by tmkklivecom** [comment]
Script says 
Advanced Media Extensions already installed

**Comment by tmkklivecom** [comment]
There is a bug in the line 481

**Comment by 007revad** [comment]
Fixed in v1.0.1 
https://github.com/007revad/Video_Station_for_DSM_722/releases
