### ISSUE TITLE
HEIC thumbnails & preview photos

### ISSUE THREAD

**Issue by visysis** [007revad/Video_Station_for_DSM_722#32]
Hi!

After installing this script, the HEIC photos preview did not work. I re-indexed all photos in the Synology Photos app, but it did not help. BTW, VideoStaion works fine. Any ideas?

<img width="1144" alt="1" src="https://github.com/user-attachments/assets/f7c0ebbf-ff82-4b85-9d8b-ca54b8932a03">
<img width="683" alt="2" src="https://github.com/user-attachments/assets/b9223acc-e87e-4356-bfbb-4160c336c608">
<img width="1696" alt="3" src="https://github.com/user-attachments/assets/1ee69d1e-23cc-4a3a-a798-19e47e3c8b0e">
<img width="626" alt="4" src="https://github.com/user-attachments/assets/36cf7032-9717-4a37-90b6-f91f2ba38509">

**Comment by 007revad** [comment]
Try enabling then disabling Shared Space.

If Shared Space is already enabled try disabling then enabling Shared Space.

**Comment by visysis** [comment]
Turned it off, turned it on, re-indexed photos, didn't help.

<img width="628" alt="5" src="https://github.com/user-attachments/assets/73280d8a-fb45-45bd-8cf7-21f4e879e798">

<img width="621" alt="6" src="https://github.com/user-attachments/assets/3a371ed2-b3a7-48ee-9196-f4b67e49791b">

<img width="625" alt="7" src="https://github.com/user-attachments/assets/a51e9d63-1cf6-4159-88f0-3b4639d9578b">

<img width="629" alt="8" src="https://github.com/user-attachments/assets/3fb427ee-0731-4a95-a1d0-3ab45fcf7bcf">

<img width="1700" alt="9" src="https://github.com/user-attachments/assets/7ea9c339-179a-4635-829f-b0f73d018250">

**Comment by visysis** [comment]
File station also does not display previews of HEIC photos.

<img width="1700" alt="10" src="https://github.com/user-attachments/assets/ac4ff1be-0a90-43e0-bfa0-b09628d2bc14">

**Comment by visysis** [comment]
I found the root cause, the problem is only with photos from IOS 18. Here is a thread discussing this issue.
https://github.com/ImageMagick/ImageMagick/discussions/7426

Photos preview from IOS 17 works correctly.

**Comment by nino070** [comment]
@visysis I am having the same issue, for iOS 18 photos no previews or thumbnails are generated.
Did you find a solution in the meantime? Could we perhaps upgrade imagemagick manually, or are we waiting for Synology to update Syno Photos?

**Comment by visysis** [comment]
> @visysis I am having the same issue, for iOS 18 photos no previews or thumbnails are generated. Did you find a solution in the meantime? Could we perhaps upgrade imagemagick manually, or are we waiting for Synology to update Syno Photos?

https://github.com/ImageMagick/ImageMagick/discussions/7426

**Comment by nino070** [comment]
@visysis  Sorry for the stupid question but did you update imagemagick directly on your Synology? Do you mind sharing the commands you used?

**Comment by visysis** [comment]
> @visysis Sorry for the stupid question but did you update imagemagick directly on your Synology? Do you mind sharing the commands you used?

This problem is not solved yet. It is necessary to rebuild ImageMagic with the new libheif library.
