### ISSUE TITLE
Let's Backup the downloads

### ISSUE THREAD

**Issue by scrapix** [007revad/Video_Station_for_DSM_722#36]
Hey, thank you for providing this!

Is it possible to save the downloaded versions, since Synology could possibly remove or being forced to remove them.
in that case we could have theme here in this github repo?

Then people could also just install one package "CodecPack-x86_64-3.1.0-3005.spk" to restore HVEC compatibility.

Thank you very much!

**Comment by 007revad** [comment]
I have the .spk files archived, just in case Synology deletes them.

**Comment by scrapix** [comment]
Is it worth attaching them to your repo?

**Comment by 007revad** [comment]
Only if Synology deletes them. Otherwise I may be risking my GitHub account if Synology lodged a copyright claim.
