### ISSUE TITLE
 Does it also support hevc decoding for synology photos?

### ISSUE THREAD

**Issue by Linjieqiang** [007revad/Video_Station_for_DSM_722#9]
Thank you for your dedication. I don't use video station, but I hope that the decoding of my photo hvec is still done on nas.

**Comment by 007revad** [comment]
I just downloaded a sample.heic photo and saved it to the photo shared folder and the Synology Photos webui shows the image, but it did not generate the thumbnails.

Next I created a folder named heic and copied sample.heic into the heic folder. Synology Photos immediately created the thumbnails.

Note: This is with the latest version of Synology Photos and the previous version of Advanced Media Extensions installed via my script and HEVC installed.

**Comment by 007revad** [comment]
The folder name can be anything. If the files are part of an album they'll already be in a folder.

**Comment by timvdsm** [comment]
Hi I'm in the same situation. I don't use Video Station but use the decoding of the heic/hevc a lot within Synology Photos. Uploading my iphone photos directly to the nas with FileBrowser. It worked perfectly in the past. Does this means this will work again as long as the photos are placed into a folder (which is always in my case)? It's just not working when you putt them in the photos root folder? Am I correct? Thx!

**Comment by 007revad** [comment]
I just tested again by renaming the heic photo in the root folder and Synology Photos generated the thumbnail. So maybe I checked too soon the first time I tested.
